services:
  frontend:
    #image: dedf1sh/bytebazaarfrontend:latest
    build:
      context: ./ByteBazaarFrontend
      dockerfile: Dockerfile
    container_name: bytebazaarfrontend
    ports:
      - "4200:80" # port 80 is nginx default
    networks:
      - bytebazaar_network
    depends_on:
      - backend
  
  backend:
    #image: dedf1sh/bytebazaarbackend:latest
    build:
      context: ./ByteBazaarBackend
      dockerfile: Dockerfile
    container_name: bytebazaarbackend
    ports:
      - "8080:8080"
    networks:
      - bytebazaar_network
    depends_on:
      - mariadb
  
  mariadb:
    image: mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_DATABASE=${DB_NAME}
    container_name: bytebazaar_db
    ports:
      - "3307:3307"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - bytebazaar_network

volumes:
  db_data:

networks:
  bytebazaar_network:
    driver: bridge